version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db

  parse:
    image: elestio/parse-server:${SOFTWARE_VERSION_TAG}
    container_name: parse
    restart: always
    ports:
      - 172.17.0.1:1337:1337
    links:
      - mongo
    environment:
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${MASTER_KEY}
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/dev
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY={"classNames":["people","monitor"]}
      - PARSE_SERVER_MASTER_KEY_IPS=0.0.0.0/0
    volumes:
      - ./parse/cloud:/parse-server/cloud
      - ./parse/config:/parse-server/config
  dashboard:
    image: elestio/parse-dashboard:${SOFTWARE_VERSION_TAG}
    container_name: dashboard
    restart: always
    ports:
      - "172.17.0.1:4040:4040"
    environment:
      - PARSE_DASHBOARD_SERVER_URL=${BASE_URL}:8443/parse
      - PARSE_DASHBOARD_APP_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_DASHBOARD_MASTER_KEY=${MASTER_KEY}
      - PARSE_DASHBOARD_APP_NAME=MyApp
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_USER_ID=${ADMIN_EMAIL}
      - PARSE_DASHBOARD_USER_PASSWORD=${ADMIN_PASSWORD}
